# Generated by Django 5.2.1 on 2025-06-06 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjango', '0002_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('attempt_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
