# Generated by Django 5.2.1 on 2025-07-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjango', '0004_postulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo_cargo', models.CharField(choices=[('uiux', 'Analista/Desarrollador UI/UX'), ('backend', 'Analista/Desarrollador Back-End'), ('comercial', 'Analista Comercial'), ('arquitecto', 'Arquitecto y Dueño de Producto'), ('director', 'Director de Proyectos Ágiles'), ('lider', 'Líder de equipo y tecnología'), ('calidad', 'Ingeniero de Calidad')], max_length=20)),
                ('rango', models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior')], max_length=10)),
                ('titulo_requerido', models.CharField(max_length=255)),
                ('requerimientos', models.TextField(blank=True, null=True)),
                ('funciones', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
