# Generated by Django 5.2.1 on 2025-07-16 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjango', '0005_ofertalaboral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulacion',
            old_name='descripcion_oferta',
            new_name='motivacion',
        ),
        migrations.RemoveField(
            model_name='postulacion',
            name='titulo_oferta',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='hoja_de_vida',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='oferta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='mydjango.ofertalaboral'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='titulo_posgrado',
            field=models.FileField(blank=True, null=True, upload_to='titulos/'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='titulo_pregrado',
            field=models.FileField(blank=True, null=True, upload_to='titulos/'),
        ),
    ]
